services:
  - type: web
    name: msme-portal
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE
        value: "false"
